#!/usr/bin/env python3
"""Flo Permit blog generator.

Run from the repo root:
    python scripts/gen_blog.py

Reads:   blog/posts/*.md
Writes:  frontend/public/blog/*.html (one page per post, plus /blog/ index)
         and refreshes frontend/public/sitemap.xml (by re-running gen_seo_pages.py)

Post format: a front matter block, then markdown.

    ---
    title: Page headline (the H1, up to 90 characters)
    seo_title: Short <title> tag, 70 characters or fewer (optional if the title is short)
    description: Meta description, 155 characters or fewer
    slug: url-slug                  (optional, defaults to the file name)
    date: 2026-10-01
    updated: 2026-10-01             (optional)
    tags: Notice of Commencement, Broward
    cities: fort-lauderdale, miami  (optional, adds a "Requirements for your city" box)
    permits: fort-lauderdale/roofing (optional, adds permit checklist links)
    status: published               (or draft)
    ---

Supported markdown: ## and ### headings, paragraphs, **bold**, *italic*, `code`, [links](url),
bullet and numbered lists, > callouts (use > [!TIP] for a green one), pipe tables, and a
"## FAQ" section (each ### is a question) which also becomes FAQPage markup.

Publishing rules (so nothing unverified goes live):
  * a post containing "[VERIFY" is never published; it is listed in the build report
  * status: draft is never published
  * every internal link must point at a page that exists, or the build fails
Use --include-drafts to preview drafts (noindex, not in the sitemap).
"""
import argparse
import datetime as dt
import html
import importlib.util
import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
MARK = "<!-- generated by scripts/gen_blog.py -->"


def load_seo():
    spec = importlib.util.spec_from_file_location("gen_seo_pages", HERE / "gen_seo_pages.py")
    mod = importlib.util.module_from_spec(spec)
    sys.modules["gen_seo_pages"] = mod
    spec.loader.exec_module(mod)
    return mod


seo = load_seo()
BASE = seo.BASE
esc = html.escape

BLOG_CSS = r"""
.post{max-width:740px;margin:0 auto;padding:40px 24px 72px}
.post .badges{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:6px}
.post .badge{display:inline-block;padding:4px 12px;border-radius:6px;font-size:11px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:#22d3ee;background:rgba(34,211,238,.08);border:1px solid rgba(34,211,238,.15)}
.post h1{font-size:clamp(28px,5vw,40px);font-weight:900;color:#fff;line-height:1.2;margin:14px 0}
.post .lede{font-size:18px;color:#94a3b8;line-height:1.6;margin:0 0 18px}
.post .byline{font-size:13px;color:#64748b;padding-bottom:20px;border-bottom:1px solid rgba(255,255,255,.06);margin-bottom:28px}
.post h2{font-size:24px;font-weight:800;color:#fff;margin:44px 0 14px;line-height:1.3}
.post h3{font-size:18px;font-weight:800;color:#e2e8f0;margin:28px 0 10px;line-height:1.35}
.post p,.post li{font-size:17px;color:#a8b4c4;line-height:1.8}
.post p{margin:0 0 18px}.post ul,.post ol{margin:0 0 20px 22px}.post li{margin-bottom:8px}
.post strong{color:#e2e8f0}.post a{color:#22d3ee}.post code{background:rgba(255,255,255,.06);padding:1px 6px;border-radius:5px;font-size:.9em}
.post hr{border:0;border-top:1px solid rgba(255,255,255,.08);margin:36px 0}
.post .tablewrap{overflow-x:auto;margin:0 0 22px}.post table{border-collapse:collapse;width:100%;min-width:560px;font-size:15px}
.post th{text-align:left;color:#e2e8f0;font-weight:700;padding:10px 12px;border-bottom:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.02)}
.post td{color:#a8b4c4;padding:10px 12px;border-bottom:1px solid rgba(255,255,255,.05);vertical-align:top}
.callout{background:rgba(245,158,11,.04);border:1px solid rgba(245,158,11,.14);border-radius:12px;padding:16px 20px;margin:22px 0}
.callout p{color:#fbbf24;font-size:15px;line-height:1.7;margin:0}
.callout-green{background:rgba(16,185,129,.04);border-color:rgba(16,185,129,.16)}.callout-green p{color:#34d399}
.toc{background:rgba(255,255,255,.02);border:1px solid rgba(255,255,255,.06);border-radius:12px;padding:16px 22px;margin:0 0 30px}
.toc strong{display:block;font-size:12px;letter-spacing:1px;text-transform:uppercase;color:#64748b;margin-bottom:8px}
.toc ol{margin:0 0 0 20px}.toc li{font-size:15px;margin-bottom:4px}
.related{margin:36px 0 0}.related h2{margin-top:0}
.post-cards{display:grid;gap:14px}
.post-card{display:block;padding:22px 24px;background:rgba(255,255,255,.02);border:1px solid rgba(255,255,255,.06);border-radius:14px}
.post-card:hover{border-color:rgba(34,211,238,.3)}.post-card h2{font-size:21px;font-weight:800;color:#fff;margin:0 0 8px;line-height:1.3}
.post-card p{font-size:15px;color:#94a3b8;margin:0 0 10px;line-height:1.6}.post-card small{font-size:12px;color:#64748b}
.draft-banner{background:#7f1d1d;color:#fecaca;text-align:center;padding:10px;font-size:13px;font-weight:700}
"""


# ---------------------------------------------------------------- markdown
def slugify(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def inline(s):
    s = esc(s, quote=False)
    s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
    s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"(?<![\w*])\*(?!\s)(.+?)(?<!\s)\*(?![\w*])", r"<em>\1</em>", s)

    def link(m):
        text, url = m.group(1), html.unescape(m.group(2))
        ext = url.startswith("http")
        return '<a href="{}"{}>{}</a>'.format(esc(url), ' rel="noopener" target="_blank"' if ext else "", text)

    return re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", link, s)


def split_row(line):
    return [c.strip() for c in line.strip().strip("|").split("|")]


def parse_blocks(text):
    lines, i, blocks = text.split("\n"), 0, []
    start_re = re.compile(r"^(#{2,3} |>|\s*[-*] |\s*\d+\. |\s*(-{3,}|\*{3,})\s*$)")
    while i < len(lines):
        ln = lines[i]
        if not ln.strip():
            i += 1
            continue
        m = re.match(r"^(#{2,3}) (.+)$", ln)
        if m:
            blocks.append(("h", len(m.group(1)), m.group(2).strip()))
            i += 1
        elif re.match(r"^\s*(-{3,}|\*{3,})\s*$", ln):
            blocks.append(("hr",))
            i += 1
        elif ln.startswith(">"):
            buf = []
            while i < len(lines) and lines[i].startswith(">"):
                buf.append(lines[i][1:].strip())
                i += 1
            green = bool(buf and buf[0].startswith("[!TIP]"))
            if green:
                buf[0] = buf[0][len("[!TIP]"):].strip()
            blocks.append(("callout", green, " ".join(b for b in buf if b)))
        elif re.match(r"^\s*[-*] ", ln):
            buf = []
            while i < len(lines) and re.match(r"^\s*[-*] ", lines[i]):
                buf.append(re.sub(r"^\s*[-*] ", "", lines[i]))
                i += 1
            blocks.append(("ul", buf))
        elif re.match(r"^\s*\d+\. ", ln):
            buf = []
            while i < len(lines) and re.match(r"^\s*\d+\. ", lines[i]):
                buf.append(re.sub(r"^\s*\d+\. ", "", lines[i]))
                i += 1
            blocks.append(("ol", buf))
        elif "|" in ln and i + 1 < len(lines) and re.match(r"^\s*\|?\s*:?-{2,}", lines[i + 1]):
            head = split_row(ln)
            i += 2
            rows = []
            while i < len(lines) and "|" in lines[i] and lines[i].strip():
                rows.append(split_row(lines[i]))
                i += 1
            blocks.append(("table", head, rows))
        else:
            buf = []
            while i < len(lines) and lines[i].strip() and not start_re.match(lines[i]):
                buf.append(lines[i].strip())
                i += 1
            blocks.append(("p", " ".join(buf)))
    return blocks


def render(blocks):
    out, heads, used = [], [], set()
    for b in blocks:
        k = b[0]
        if k == "h":
            hid = base = slugify(b[2])
            n = 2
            while hid in used:
                hid, n = "{}-{}".format(base, n), n + 1
            used.add(hid)
            heads.append((b[1], hid, b[2]))
            out.append('<h{l} id="{i}">{t}</h{l}>'.format(l=b[1], i=hid, t=inline(b[2])))
        elif k == "p":
            out.append("<p>{}</p>".format(inline(b[1])))
        elif k == "hr":
            out.append("<hr>")
        elif k == "callout":
            out.append('<div class="callout{}"><p>{}</p></div>'.format(" callout-green" if b[1] else "", inline(b[2])))
        elif k in ("ul", "ol"):
            out.append("<{t}>{li}</{t}>".format(t=k, li="".join("<li>{}</li>".format(inline(x)) for x in b[1])))
        elif k == "table":
            th = "".join("<th>{}</th>".format(inline(c)) for c in b[1])
            tr = "".join("<tr>{}</tr>".format("".join("<td>{}</td>".format(inline(c)) for c in r)) for r in b[2])
            out.append('<div class="tablewrap"><table><thead><tr>{}</tr></thead><tbody>{}</tbody></table></div>'.format(th, tr))
    return "\n".join(out), heads


def extract_faq(blocks):
    faq, in_faq, q, ans = [], False, None, []

    def flush():
        if q and ans:
            faq.append((q, " ".join(ans)))

    for b in blocks:
        if b[0] == "h" and b[1] == 2:
            flush()
            q, ans = None, []
            in_faq = b[2].strip().lower() in ("faq", "frequently asked questions")
        elif in_faq and b[0] == "h" and b[1] == 3:
            flush()
            q, ans = b[2], []
        elif in_faq and q and b[0] == "p":
            ans.append(re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", re.sub(r"[*`]", "", b[1])))
    flush()
    return faq


# ---------------------------------------------------------------- posts
def parse_post(path):
    raw = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", raw, re.S)
    if not m:
        raise SystemExit("{}: missing front matter block".format(path.name))
    meta = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            meta[k.strip().lower()] = v.strip()
    for req in ("title", "description", "date"):
        if not meta.get(req):
            raise SystemExit("{}: front matter needs '{}'".format(path.name, req))
    meta.setdefault("slug", path.stem)
    meta.setdefault("updated", meta["date"])
    meta.setdefault("status", "published")
    for k in ("tags", "cities", "permits"):
        meta[k] = [x.strip() for x in meta.get(k, "").split(",") if x.strip()]
    meta["body"] = m.group(2).strip()
    meta["file"] = path.name
    return meta


def city_lookup(public):
    names = {}
    for f in (public / "cities").glob("*.html"):
        h = f.read_text(encoding="utf-8", errors="ignore")
        m = re.search(r"<h1><em>(.*?)</em> Permit Requirements</h1>", h)
        if m and f.stem not in ("index",) and not f.stem.endswith("-county"):
            names[f.stem] = html.unescape(m.group(1))
    return names


def internal_targets_ok(public, hrefs):
    bad = []
    for href in hrefs:
        p = href.split("#")[0].split("?")[0]
        if not p or p == "/":
            continue
        rel = p.lstrip("/") + ("index.html" if p.endswith("/") else "")
        if not (public / rel).exists() and not rel.startswith(("adc_logo", "demo")):
            bad.append(href)
    return bad


def build_post(p, public, cities, today, draft):
    blocks = parse_blocks(p["body"])
    body_html, heads = render(blocks)
    faq = extract_faq(blocks)
    url = "{}/blog/{}.html".format(BASE, p["slug"])
    words = len(re.sub(r"<[^>]+>", " ", body_html).split())
    mins = max(1, round(words / 210))

    h2s = [(i, t) for lvl, i, t in heads if lvl == 2 and t.strip().lower() not in ("faq", "frequently asked questions", "sources")]
    toc = ""
    if len(h2s) >= 4:
        toc = '<div class="toc"><strong>On this page</strong><ol>{}</ol></div>'.format("".join('<li><a href="#{}">{}</a></li>'.format(i, esc(re.sub(r"^\d+\.\s*", "", t))) for i, t in h2s))

    rel = []
    for c in p["cities"]:
        if c in cities:
            rel.append(("/cities/{}.html".format(c), "{} permit requirements".format(cities[c]), "All permit types and rejection reasons"))
    for pm in p["permits"]:
        c, _, t = pm.partition("/")
        pth = "/cities/{}/{}.html".format(c, t)
        if (public / pth.lstrip("/")).exists():
            rel.append((pth, "{} {} checklist".format(cities.get(c, c), t.replace("-", " ")), "Full checklist for this permit type"))
    related = ""
    if rel:
        related = '<div class="related"><h2>Requirements for your city</h2>{}</div>'.format(seo.link_cards(rel))

    cta = ('<div class="cta-box" style="margin-top:44px"><h2>Check your package before you submit.</h2><p>Upload your documents and see what is missing against your city\'s checklist.</p>'
           '{}<p style="margin-top:14px;margin-bottom:0;font-size:12px;color:#475569">3 free analyses to start. No credit card needed.</p></div>').format(seo.hero_cta("Start Free Analysis \u2192"))
    note = '<p style="font-size:14px;color:#64748b;margin-top:28px"><em>General information, not legal advice. Requirements change, so confirm current rules with your building department.</em></p>'
    crumbs = [("Home", "/"), ("Blog", "/blog/"), (p["title"], "/blog/{}.html".format(p["slug"]))]
    badges = "".join('<span class="badge">{}</span>'.format(esc(t)) for t in p["tags"][:3])
    pub, upd = p["date"], p["updated"]
    byline = "By Alex Calvo &middot; Published {} &middot; {}{} min read".format(pub, "Updated {} &middot; ".format(upd) if upd != pub else "", mins)
    banner = '<div class="draft-banner">DRAFT PREVIEW. Not published. Not indexed.</div>' if draft else ""
    body = (banner + seo.nav() + seo.crumbs_html(crumbs) + '<article class="post"><div class="badges">{}</div><h1>{}</h1><p class="lede">{}</p><div class="byline">{}</div>{}{}{}{}{}</article>'.format(
        badges, esc(p["title"]), esc(p["description"]), byline, toc, body_html, related, cta, note) + seo.footer(today))

    graph = [
        {"@type": "Organization", "@id": BASE + "/#org", "name": "Flo Permit", "url": BASE + "/", "logo": BASE + "/adc_logo.png"},
        {"@type": "Article", "@id": url + "#article", "headline": p["title"], "description": p["description"], "datePublished": pub, "dateModified": upd,
         "author": {"@type": "Person", "name": "Alex Calvo"}, "publisher": {"@id": BASE + "/#org"}, "mainEntityOfPage": url, "image": BASE + "/adc_logo.png", "wordCount": words},
        {"@type": "BreadcrumbList", "itemListElement": [{"@type": "ListItem", "position": i + 1, "name": n, "item": BASE + pth} for i, (n, pth) in enumerate(crumbs)]},
    ]
    if len(faq) >= 2:
        graph.append({"@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a}} for q, a in faq]})
    extra_head = ('<meta property="article:published_time" content="{}"><meta property="article:modified_time" content="{}">'.format(pub, upd))
    tt = p.get("seo_title") or p["title"]
    if len(tt) + 13 <= 70:
        tt += " | Flo Permit"
    doc = seo.shell(tt, p["description"], url, body, graph, extra_css=BLOG_CSS, og_type="article",
                    robots="noindex, nofollow" if draft else "index, follow, max-image-preview:large", extra_head=extra_head)
    return doc.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + MARK, 1), body_html


def build_index(posts, today):
    url = BASE + "/blog/"
    title = "Florida Permit Guides and Checklists | Flo Permit Blog"
    desc = "Plain English guides for Florida contractors: permit checklists, Notice of Commencement rules, HVHZ requirements and common rejection reasons."
    cards = "".join(
        '<a class="post-card" href="/blog/{s}.html"><h2>{t}</h2><p>{d}</p><small>{dt} &middot; {tags}</small></a>'.format(
            s=p["slug"], t=esc(p["title"]), d=esc(p["description"]), dt=p["date"], tags=esc(", ".join(p["tags"][:2])))
        for p in sorted(posts, key=lambda x: (x["date"], x["slug"]), reverse=True))
    crumbs = [("Home", "/"), ("Blog", "/blog/")]
    body = (seo.nav() + seo.crumbs_html(crumbs) + '<div class="hero"><h1>Florida <em>Permit Guides</em></h1><p class="hero-sub">Checklists, rules and rejection reasons for South Florida contractors, written from the same requirements data behind our city pages.</p></div>'
            + '<div class="section"><div class="post-cards">{}</div><p style="margin-top:28px"><a href="/cities/">Browse permit requirements by city \u2192</a></p></div>'.format(cards) + seo.footer(today))
    graph = seo.graph_base(url, title, desc, today, crumbs)
    doc = seo.shell(title, desc, url, body, graph, extra_css=BLOG_CSS)
    return doc.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + MARK, 1)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--posts", default=str(ROOT / "blog" / "posts"))
    ap.add_argument("--public", default=str(ROOT / "frontend" / "public"))
    ap.add_argument("--data", default=str(ROOT / "backend" / "permit_data.py"))
    ap.add_argument("--date", default=dt.date.today().isoformat())
    ap.add_argument("--include-drafts", action="store_true")
    ap.add_argument("--skip-seo", action="store_true", help="do not run gen_seo_pages.py before/after")
    a = ap.parse_args()
    public, today = Path(a.public), a.date
    seo_cmd = [sys.executable, str(HERE / "gen_seo_pages.py"), "--data", a.data, "--out", str(public), "--date", today]

    # 1) make sure the city pages exist so internal links can be validated
    if not a.skip_seo:
        subprocess.run(seo_cmd, check=True, stdout=subprocess.DEVNULL)
    cities = city_lookup(public)

    posts = [parse_post(f) for f in sorted(Path(a.posts).glob("*.md"))]
    slugs = [p["slug"] for p in posts]
    if len(slugs) != len(set(slugs)):
        raise SystemExit("duplicate slug in blog/posts")
    blog = public / "blog"
    blog.mkdir(parents=True, exist_ok=True)
    for old in blog.glob("*.html"):   # remove pages this script made earlier (and nothing else)
        if MARK in old.read_text(encoding="utf-8", errors="ignore"):
            old.unlink()

    published, held, errors, built = [], [], [], []
    for p in posts:
        verify = re.findall(r"\[VERIFY[^\]]*\]", p["body"] + p["title"] + p["description"])
        draft = p["status"] != "published" or bool(verify)
        if len(p["description"]) > 155:
            errors.append("{}: description is {} chars (max 155)".format(p["file"], len(p["description"])))
        if len(p.get("seo_title") or p["title"]) > 70:
            errors.append("{}: add a seo_title of 70 characters or fewer (the <title> tag is {} chars)".format(p["file"], len(p.get("seo_title") or p["title"])))
        if len(p["title"]) > 90:
            errors.append("{}: title is {} chars (max 90)".format(p["file"], len(p["title"])))
        if draft and not a.include_drafts:
            held.append((p["file"], "status: draft" if p["status"] != "published" else "{} [VERIFY] marker(s)".format(len(verify))))
            continue
        doc, body_html = build_post(p, public, cities, today, draft)
        built.append((p, doc, body_html, draft))

    # validate internal links once every post is known (posts may link to each other)
    blog_urls = {"/blog/"} | {"/blog/{}.html".format(p["slug"]) for p, _, _, d in built if not d or a.include_drafts}
    for p, doc, body_html, draft in built:
        bad = [h for h in internal_targets_ok(public, re.findall(r'href="(/[^"]*)"', body_html)) if h.split("#")[0] not in blog_urls]
        if bad:
            errors.append("{}: internal link(s) to pages that do not exist: {}".format(p["file"], ", ".join(sorted(set(bad)))))
    if errors:
        print("\nBUILD FAILED:")
        [print("  -", e) for e in errors]
        sys.exit(1)
    for p, doc, body_html, draft in built:
        (blog / "{}.html".format(p["slug"])).write_text(doc, encoding="utf-8")
        if not draft:
            published.append(p)
    (blog / "index.html").write_text(build_index(published, today), encoding="utf-8")

    # 2) rebuild the sitemap so it includes the blog index and every published post
    if not a.skip_seo:
        subprocess.run(seo_cmd, check=True, stdout=subprocess.DEVNULL)
    print("Blog: {} published | {} held back | index: /blog/".format(len(published), len(held)))
    for f, why in held:
        print("  HELD  {}  ({})".format(f, why))
    for p in published:
        print("  LIVE  /blog/{}.html  ({})".format(p["slug"], p["title"][:70]))


if __name__ == "__main__":
    main()
